wrap_comments = true
comment_width = 120
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
doc_comment_code_block_width = 80  # very useful when docs are open side by side
format_strings = true
max_width = 120
imports_granularity = "Crate"
newline_style = "Unix"
reorder_impl_items = true
group_imports = "StdExternalCrate"
